TiendaOnline/Areas/Admin/Controllers/GestorClientesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TiendaOnline.Data;

namespace TiendaOnline.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class GestorClientesController : Controller
    {
        UserManager<IdentityUser> userManager;
        ApplicationDbContext _db;
        public GestorClientesController(UserManager<IdentityUser> _userManager, ApplicationDbContext db)
        {
            userManager = _userManager;
            _db = db;
        }

        public IActionResult Index()
        {

            return View(_db.ApplicationUsers.ToList());


        }

        public IActionResult VisualizarCompras(string id)
        {
            var user = _db.ApplicationUsers.FirstOrDefault(c => c.Id == id);

            var product = _db.Carrito.Include(c => c.Producto).Where(c => c.email == user.UserName).ToList();
            return View(product);
        }
    }
}

TiendaOnline/Areas/Admin/Views/GestorClientes/Index.cshtml
@model IEnumerable<TiendaOnline.Models.ApplicationUser>
@{
    ViewData["Title"] = "Index";
}

<br />
<br />
<div class="container">
    <div class="row">
        <div class="col-6">
            <h2 class="text-info">Lista de Clientes</h2>
        </div>

    </div>
    <br />

    <div>
        <table class="table table-striped border text-center">

            <tr class="table-info">
                <th>Correo del Usuario</th>
                <th>Acción</th>
            </tr>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.UserName</td>
                    <td style="width: 150px">
                        <a asp-action="VisualizarCompras" class="btn_3 p-2" asp-route-id="@item.Id">
                            Ver Compras
                        </a>
                    </td>


                </tr>
            }
        </table>
    </div>

</div>

TiendaOnline/Areas/Admin/Views/GestorClientes/VisualizarCompras.cshtml
@using TiendaOnline.Models
@model List<Carrito>
@{
    ViewData["Title"] = "Cart";
}
    <br />
    <div class="container">
        <h1>Compras del Cliente</h1>


        <div class="row">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>Imagen </th>
                        <th>Nombre </th>
                        <th>Cantidad</th>
                        <th>Precio</th>

                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                <img src="~/@item.Producto.Imagen" width="200" height="150" />
                            </td>
                            <td>@item.Producto.Nombre</td>
                            <td>@item.Cantidad</td>
                            <td>@item.Producto.Precio  </td>


                        </tr>
                    }
                </tbody>
            </table>
        </div>
        <div class="row">
            @*<div class="col-6">
                <a asp-action="Index" asp-controller="Home" class="btn btn-success">Volver al principio</a>
            </div>*@
            <div class="col-6 text-right">
                <h3>Cantidad Total</h3>
                <h3>Total Cuenta: @Model.Sum(c => c.Producto.Precio)</h3>
                <a asp-area="Admin" asp-action="Index" asp-controller="GestorClientes" class="btn_3">Volver a Lista de Clientes</a>


            </div>

        </div>

    </div>