TiendaOnline/Models/Carrito.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace TiendaOnline.Models
{
    public class Carrito
    {
        [Key]
        public int Id { get; set; }
        public int Cantidad { get; set; }
        public string email { get; set; }
        public int ProductId { get; set; }
        [ForeignKey("ProductId")]
        public Productos Producto { get; set; }
    }
}

TiendaOnline/Areas/Cliente/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TiendaOnline.Data;
using TiendaOnline.Models;
using TiendaOnline.Utilidades;
using X.PagedList;

namespace TiendaOnline.Controllers
{

    [Area("Cliente")]

    public class HomeController : Controller
    {

        private ApplicationDbContext _db;

        public HomeController (ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index(/*int? page*/)
        {
            ProductosSlider ps = new ProductosSlider();
            ps.productos = _db.Productos.ToList();
            ps.sliders = _db.Slider.ToList();
            return View(ps);
           // return View(_db.Productos.Include(c=>c.CategoriaProductos).ToList().ToPagedList(page??1, 6));

        }
        public async Task<IActionResult> Resultados(string busqueda)
        {

            ViewData["FILTRO"] = busqueda;
            var productos = from s in _db.Productos select s;
            if (!String.IsNullOrEmpty(busqueda))
            {
                productos = productos.Where(s => s.Nombre.Contains(busqueda));

                if (productos.Count() == 0)
                {
                    return RedirectToAction(nameof(notresultado));
                }
            }
            
            return View(productos.ToList());

        }
        public IActionResult notresultado()
        {
            @ViewData["NORESULTADO"] = "NO SE ENCONTRARON RESULTADOS DE SU BUSQUEDA";
            return View();
        }




        public IActionResult Inicio(int? page)
        {

            ProductosSlider ps = new ProductosSlider();
            ps.productos = _db.Productos.ToList();
            ps.sliders = _db.Slider.ToList();
            return View(ps);
            //return View(_db.Productos.Include(c => c.CategoriaProductos).ToList().ToPagedList(page ?? 1, 6));
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }



        public ActionResult Detail(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var product = _db.Productos.Include(c => c.CategoriaProductos).FirstOrDefault(c => c.ID == id);
            if (product == null)
            {
                return NotFound();

            }
            return View(product);
        }

        [HttpPost]
        [ActionName("Detail")]
        public async Task<ActionResult> ProductDetail(int? id)
        {
            Carrito cr = new Carrito();
            List<Productos> producto = _db.Productos.Include(c => c.CategoriaProductos).Where(c => c.ID == id).ToList();

            if (producto != null)
            {
                foreach (var prod in producto)
                {
                    cr.ProductId = prod.ID;
                }
            }

            cr.email = User.Identity.Name;

            cr.Cantidad = 1;

            await _db.Carrito.AddAsync(cr);

            _db.SaveChanges();

            
            return RedirectToAction(nameof(Index));


        }



        //Detalles de Producto

        //public ActionResult Detail(int? id)
        //{

        //    if(id == null)
        //    {
        //        return NotFound();
        //    }

        //    var producto = _db.Productos.Include(c => c.CategoriaProductos).FirstOrDefault(c => c.ID == id);

        //    if (producto == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(producto);
        //}


        ////Post Detalles de Producto
        //[HttpPost]
        //[ActionName("Detail")]
        //public ActionResult ProductoDetail(int? id)
        //{

        //    List<Productos> productos = new List<Productos>();

        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var producto = _db.Productos.Include(c => c.CategoriaProductos).FirstOrDefault(c => c.ID == id);

        //    if (producto == null)
        //    {
        //        return NotFound();
        //    }


        //    productos = HttpContext.Session.Get<List<Productos>>("productos");
        //    if (productos == null)
        //    {
        //        productos = new List<Productos>();
        //    }
        //    productos.Add(producto);
        //    HttpContext.Session.Set("productos", productos);
        //    return RedirectToAction(nameof(Index));
        //}

        //Get Remove



        public async Task<IActionResult> Remove(int? id, Carrito ca)
        {
            if (id == null)
            {
                return NotFound();
            }
            if (id != ca.Id)
            {
                return NotFound();
            }

            var car = _db.Carrito.Find(id);
            if (car == null)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                _db.Remove(car);
                await _db.SaveChangesAsync();
                return RedirectToAction(actionName: nameof(Carrito));
            }
            return View(car);
        }

        [Authorize]
        public IActionResult Carrito()
        {

            var product = _db.Carrito.Include(c => c.Producto).Where(c => c.email == User.Identity.Name).ToList();
            return View(product);
        }



        //public IActionResult Remove(int? id)
        //{

        //    List<Productos> productos = HttpContext.Session.Get<List<Productos>>("productos");
        //    if (productos != null)
        //    {
        //        var producto = productos.FirstOrDefault(c => c.ID == id);
        //        if (producto != null)
        //        {
        //            productos.Remove(producto);
        //            HttpContext.Session.Set("productos", productos);
        //        }
        //    }
        //    return RedirectToAction(nameof(Index));
        //}




        //Producto Carrito

        //public IActionResult Carrito()
        //{
        //    List<Productos> productos = HttpContext.Session.Get<List<Productos>>("productos");
        //    if (productos == null)
        //    {
        //        productos = new List<Productos>();
        //    }
        //    return View(productos);
        //}

    }
}

TiendaOnline/Areas/Cliente/Controllers/OrdenController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Infrastructure;
using TiendaOnline.Data;
using TiendaOnline.Models;
using TiendaOnline.Utilidades;

namespace TiendaOnline.Areas.Cliente.Controllers
{
    [Area("Cliente")]

    public class OrdenController : Controller
    {

        ApplicationDbContext _db;
        SignInManager<IdentityUser> _SignInManager;

        public OrdenController(ApplicationDbContext db, SignInManager<IdentityUser> SignInManager)
        {
            _db = db;
            _SignInManager = SignInManager;
        }


        [Authorize]
        public IActionResult ConsultarOrdenes()
        {

            if (_SignInManager.IsSignedIn(User))
            {

                string email = User.Identity.Name;
                return View(_db.Orden.Where(c => c.Correo == email).ToList());
            }
            return View();

        }


        //Checkout Action Method

        public IActionResult Checkout()
        {
            return View();
        }

        //Post Checkout
        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> Checkout(Orden ord)
        {

            List<Productos> productos = HttpContext.Session.Get<List<Productos>>("productos");
            if (productos != null)
            {
                foreach(var producto in productos)
                {
                    OrdenDetalles ordenDetalles = new OrdenDetalles();
                    ordenDetalles.ProductoID = producto.ID;
                    ord.OrdenDetalles.Add(ordenDetalles);
                }
            }

            if (_SignInManager.IsSignedIn(User))
            {
                ord.Correo = User.Identity.Name;
            }
            ord.numeroOrden = obtenerNumeroOrden();
            ord.Estado = "En proceso";
            _db.Orden.Add(ord);
            await _db.SaveChangesAsync();
            HttpContext.Session.Set("productos", new List<Productos>());

            return View();
        }

        public string obtenerNumeroOrden()
        {//Count () + 1
            int conteoFila = _db.Orden.ToList().Count() + 1;
            return conteoFila.ToString("000");
        }



        public IActionResult Index()
        {
            return View(_db.Orden.ToList());
        }

        public ActionResult Edit(int? id)
        {

            if (id == null)
            {
                return NotFound();
            }
            var ordenes = _db.Orden.Find(id);
            if (ordenes == null)
            {
                return NotFound();
            }

            return View(ordenes);
        }

        //Crear el metodo Post Editar

        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> Edit(Orden ordenes)
        {
            if (ModelState.IsValid)
            {
                _db.Update(ordenes);
                await _db.SaveChangesAsync();
                TempData["editar"] = "La orden se actualizó correctamente!";
                return RedirectToAction(nameof(Index));
            }
            return View(ordenes);
        }


        [HttpGet]
        public IActionResult Mapa()
        {
            return View(_db.Orden.ToList());
        }

        [HttpPost]
        public IActionResult Mapa(string estado)
        {
            ViewData["Estado"] = estado;
            return View(_db.Orden.ToList());
        }


        
    }
}

TiendaOnline/Areas/Cliente/Views/Home/Carrito.cshtml
@using TiendaOnline.Models
@model List<Carrito>
@{
    ViewData["Title"] = "Carrito";
}

<br />

@*<br />
<div class="row">
    <table class="table table-bordered text-center">
        <thead>
            <tr>
                <th>Imagen</th>
                <th>Nombre</th>
                <th>Precio</th>
                <th>Categoria del Producto</th>
                <th>Detalles</th>
                <th>Accion</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var k in Model)
            {
                <tr>
                    <td>
                        <img src="~/@k.Imagen" width="200px" height="150px" />
                    </td>
                    <td>@k.Nombre</td>
                    <td>@k.Precio</td>
                    <td>@k.CategoriaProductos.nombreCategoria</td>
                    <td>@k.Detalles</td>
                    <td>
                        <a asp-area="Cliente" asp-action="Remove" asp-controller="Home" asp-route-id="@k.ID" class="btn btn-danger">
                            Eliminar
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

<div class="row">

    <div class="col-6">
        <a asp-action="Index" asp-controller="Home" class="btn btn-success">Volver al Inicio</a>
    </div>
    <div class="col-6 text-right">
        <h3>Precio Total</h3>
        <h3>Total Facturado : $@Model.Sum(c => c.Precio)</h3>
        <a asp-area="Cliente" asp-action="Checkout" asp-controller="Orden" class="btn btn-info">Verificar</a>
    </div>

</div>*@

<section class="cart_area ">
    <div class="container">
        <div class="cart_inner">
            <div class="table-responsive">
                <h1>Carrito</h1>
                <br />
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col" style="font-size:18px; color:black;">Producto</th>
                            <th scope="col" style="font-size:18px; color:black;">Nombre</th>
                            <th scope="col" style="font-size:18px; color:black;">Precio</th>
                            <th scope="col" style="font-size:18px; color:black;">Eliminar</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var k in Model)
                        {

                            <tr>
                                <td>
                                    <div class="media">
                                        <div class="d-flex">
                                            <img src="~/@k.Producto.Imagen" />
                                        </div>
                                        @*<div class="media-body">
                                    <p>@k.Producto.Nombre</p>
                                </div>*@
                                    </div>
                                </td>
                                <td>
                                    @k.Producto.Nombre
                                </td>
                                @*<td>
                            <h5>@k.CategoriaProductos.nombreCategoria</h5>
                        </td>*@
                                <td>
                                    <h5>@k.Producto.Precio</h5>
                                </td>
                                <td>
                                    <a class="btn_3 p-2" asp-area="Cliente" asp-action="Remove" asp-controller="Home" asp-route-id="@k.Id">
                                        Eliminar
                                    </a>
                                </td>
                                @*<td>
                            <h5 class="text-center">
                                <span class="fas fa-trash-alt button button-contactForm"><a asp-area="Cliente" asp-action="Remove" asp-controller="Home" asp-route-id="@k.Id"></a></span>
                            </h5>
                        </td>*@
                            </tr>


                        }

                    </tbody>
                </table>
                <br />
                <div class="text-right">
                    <h5 class="" style="font-size:20px; color:black;">Monto Total: </h5>
                    <h5 style="font-size:20px; color:black;">$@Model.Sum(c => c.Producto.Precio)</h5>
                </div>
                <br />
                <div class="">
                    <a class="btn_3  text-center col-sm-2 col-md-3" asp-action="Index" asp-controller="Home">Seguir con la compra</a>

                    <form action="https://www.sandbox.paypal.com/cgi-bin/webscr" method="post">
                        <input type="hidden" name="cmd" value="_xclick">
                        <input type="hidden" name="business" value="verlyn2800@gmail.com">
                        <input type="hidden" name="item_name" value="Premium Subscription">
                        <input type="hidden" name="currency_code" value="USD">
                        <input type="hidden" name="amount" value="@Model.Sum(c => c.Producto.Precio)">

                        <input type="submit" value="Hacer Pago" class="btn_1 checkout_btn_1 float-right col-sm-2 col-md-3 text-center mt-md-0 mt-sm-3"
                               src="http://www.paypal.com/es_XC/i/btn/x-click-but01.gif"
                               name="submit" alt="Make payments with PayPal - it's fast, free and secure!">

                        <input type="hidden" name="return" value="https://localhost:44387/Cliente/Orden/Checkout/pagado.php">
                        <input type="hidden" name="cancel_return" value="https://localhost:44387/Cliente/Home/Carrito/cancelado.php">

                    </form>

                </div>

            </div>
        </div>
    </div>

</section>
<!--================End Cart Area =================-->

TiendaOnline/Areas/Cliente/Views/Home/Detail.cshtml
@model TiendaOnline.Models.Productos
@{
    ViewData["Title"] = "Detalles del Producto";
}
@using TiendaOnline.Utilidades
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor
@{


    List<Productos> productos = HttpContextAccessor.HttpContext.Session.Get<List<Productos>>("productos");
    Productos producto = null;
    if (productos != null)
    {
        producto = productos.FirstOrDefault(c => c.ID == Model.ID);
    }


}
<br />
<br />
<div class="container">

    <h2 class="text-info"> Detalles del Producto</h2>

    <form asp-action="" method="post" enctype="multipart/form-data">
        <div class="p-4 rounded border row">
            <div asp-validation-summary="ModelOnly" class="text-danger">

            </div>

            <div class="col-8">

                <div class="form-group row">
                    <div class="col-2">
                        <label asp-for="Nombre"></label>
                    </div>
                    <div class="col-5">
                        <input type="hidden" asp-for="ID" />
                        <input asp-for="Nombre" readonly="readonly" class="form-control" />
                    </div>
                    <span asp-validation-for="Nombre" class="text-danger"></span>
                </div>

                <div class="form-group row">
                    <div class="col-2">
                        <label asp-for="Precio"></label>
                    </div>
                    <div class="col-5">
                        <input asp-for="Precio" readonly="readonly" class="form-control" />
                    </div>
                    <span asp-validation-for="Precio" class="text-danger"></span>
                </div>


                <div class="form-group row">
                    <div class="col-2">
                        <label asp-for="Detalles"></label>
                    </div>
                    <div class="col-5">
                        <input asp-for="Detalles" readonly="readonly" class="form-control" />
                    </div>
                    <span asp-validation-for="Detalles" class="text-danger"></span>
                </div>


                @*<div class="form-group row">
            <div class="col-2">
                <label asp-for="Imagen"></label>
            </div>
            <div class="col-5">
                <input asp-for="Imagen" readonly="readonly" class="form-control-file" type="file" />
            </div>
            <span asp-validation-for="Imagen" class="text-danger"></span>
        </div>*@



                <div class="form-group row">
                    <div class="col-2">
                        <label asp-for="CategoriaProductoId"></label>
                    </div>
                    <div class="col-5">
                        @*<select asp-for="CategoriaProductoId" asp-items="ViewBag.categoriaProductoId" class="form-control"></select>*@
                        <input asp-for="CategoriaProductoId" readonly="readonly" class="form-control" />
                    </div>
                    <span asp-validation-for="CategoriaProductoId" class="text-danger"></span>
                </div>



                <div class="form-group row">
                    <div class="col-2">
                    </div>
                    <div class="col-5">
                        @if (producto != null)
        {
            <button type="submit" class="btn btn-danger" asp-action="Remove" asp-route-id="@Model.ID">Eliminar del Carrito</button>
        }

        <input type="submit" class="btn btn-info form-control" value="Agregar al carrito" />


                        @*@if (producto != null)
                        {
                            <button type="submit" class="btn btn-danger" asp-action="Remove" asp-route-id="@Model.ID">Eliminar del Carrito</button>
                        }
                        else if (Model.Disponibilidad != true)
                        {
                            <input type="submit" class="btn btn-success" value="Agregar al Carrito" disabled />
                        }
                        else
                        {
                            <input type="submit" class="btn btn-success" value="Agregar al Carrito" />
                        }*@


                        @*else if (producto.Disponibilidad != true)
        {

            <input type="submit" class="btn btn-success " value="Agregar al Carrito" disabled />
        }
        else
        {
            <button type="submit" value="Agregar" class="btn_3 p-3">
                Agregar
            </button>
        }
        <button asp-action="Index" class="btn_3 p-3">
            Cancelar
        </button>*@
                    </div>
                   
                </div>
                <br />

                <div class="col-md-6 form-group">
                    
                  
                </div>


            </div>
            <div class="col-4">
                <img src="~/@Model.Imagen"  style="width:80%;border-radius: 1px; border: 2px solid #0094ff" />
                <br />
                <br />
                &nbsp &nbsp &nbsp &nbsp
                @if (Model.Disponibilidad == true)
                {
                    <img src="~/Imagenes/Disponible.png" style="width:200px; height:125px;" />
                }
                else
                {
                    <img src="~/Imagenes/NoDisponible.jpg" style="width:200px; height:125px;" />

                }
            </div>



        </div>
    </form>
 </div>


    @section Scripts{
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");
        }
    }

TiendaOnline/Areas/Cliente/Views/Home/Index.cshtml
@*@using TiendaOnline.Models;
    @using X.PagedList.Mvc.Core
    @model X.PagedList.IPagedList<Productos>*@

@using TiendaOnline.Models
@model ProductosSlider

@{
    ViewData["Title"] = "Inicio";
}


<br />
<br />

@*<div class="row">
        @foreach (var producto in Model)
        {
            <div class="col-4">
                <div class="card mb-4">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">
                            <label style="font-size: 23px; color:steelblue"><strong>@producto.Nombre</strong></label >
                        </h4>
                    </div>
                    <img src="~/@producto.Imagen" alt="Card Imagen" class="card-img-top" style="width:100%; height:300px;"  />
                    <div class="card-header">
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <label style="font-size:20px; color:#f31212">
                                    <b>Precio : <strong> $@producto.Precio </strong></b>
                                </label> &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp
                                <a asp-action="Detail" asp-controller="Home" asp-route-id="@producto.ID" class="btn btn-outline-primary">Detalles</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>*@

<div class="container">

    @*<div id="carousel" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
            @{Boolean first = true;}
            @foreach (Slider item in Model.sliders)
            {
                <div class="carousel-item  @(first?"active": "")">
                    <img style="width:1050px; height:550px" src="~/@item.image" alt="Slider" />
                </div>

                first = false;
            }

        </div>
        <a class="carousel-control-prev" data-target="#carousel" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" data-target="#carousel" data-slide="next">
            <span class="carousel-control-next-icon"></span>
            <span class="sr-only">Next</span>
        </a>

    </div>*@

    <br />

    <div class="row justify-content-center">
        <div class="col-xl-7 col-lg-8 col-md-10">
            <div class="section-tittle mb-70 text-center">
                <h2>Todos los productos</h2>
            </div>
        </div>
    </div>
    <!--? Popular Items Start -->
    <div class="popular-items">
        <div class="container">
            <!-- Section tittle -->
            <div class="row">

                @foreach (var producto in Model.productos)
                {
                    <div class="col-xl-4 col-lg-4 col-md-6 col-sm-6">
                        <div class="single-popular-items mb-50 text-center">
                            <div class="popular-img">
                                @*<img src="~/TimeZone/assets/img/gallery/popular1.png" alt="">*@

                                <img src="~/@producto.Imagen" alt="">
                                <div class="img-cap">
                                    <span class="p-2"><a asp-action="Detail" asp-controller="Home" asp-route-id="@producto.ID" class="button boxed-btn" style="border:none;">Detalles</a></span>
                                </div>
                                <div class="favorit-items">
                                    <span class="flaticon-heart"></span>
                                </div>
                            </div>
                            <div class="popular-caption">
                                <h3><a href="product_details.html">@producto.Nombre</a></h3>
                                <span> $@producto.Precio</span>
                            </div>
                        </div>
                    </div>

                }
            </div>

            <!-- Button -->

        </div>
    </div>
</div>
<!-- Popular Items End -->

@*<div>
    @Html.PagedListPager(Model, c => Href("~/Cliente/Home/Index?page=" + c), X.PagedList.Web.Common.PagedListRenderOptionsBase.PageNumbersOnly)
</div>*@

TiendaOnline/Areas/Cliente/Views/Home/Resultados.cshtml
@using TiendaOnline.Models;


@{ ViewData["Title"] = "Inicio"; }


<br />
<br />


<div class="row justify-content-center">
    <div class="col-xl-7 col-lg-8 col-md-10">
        <div class="section-tittle mb-70 text-center">
            <h2>Todos los productos</h2>
        </div>
    </div>
</div>

<!--? Popular Items Start -->
<div class="popular-items">
    <div class="container">
        <!-- Section tittle -->
        <div class="row">

            @foreach (var producto in Model)
            {
<div class="col-xl-4 col-lg-4 col-md-6 col-sm-6">
    <div class="single-popular-items mb-50 text-center">
        <div class="popular-img">
            @*<img src="~/TimeZone/assets/img/gallery/popular1.png" alt="">*@

            <img src="~/@producto.Imagen" alt="">
            <div class="img-cap">
                <span class="p-2"><a asp-action="Detail" asp-controller="Home" asp-route-id="@producto.ID" class="button boxed-btn" style="border:none;">Detalles</a></span>
            </div>
            <div class="favorit-items">
                <span class="flaticon-heart"></span>
            </div>
        </div>
        <div class="popular-caption">
            <h3><a href="product_details.html">@producto.Nombre</a></h3>
            <span> $@producto.Precio</span>
        </div>
    </div>
</div>}
        </div>

        <!-- Button -->

    </div>
</div>

TiendaOnline/Areas/Cliente/Views/Home/notresultado.cshtml
<style>
    #notret {
        color: red;
    }
</style>
<h2 id="notret"><center>@ViewData["NORESULTADO"]</center></h2>